eno=int(input('Enter employee number'))
ename=input('Enter employee name')
esal=float(input('Enter employee salary'))
ecity=input('Enter employee city')
print('Please confirm your information')
print('Employee number',eno)
print('Employee name',ename)
print('Employee salary',esal)
print('Employee number',ecity)
